const PDFDocument = require('pdfkit');

/**
 * Generate PDF summary report
 * @param {object} reportData - Report data from agents
 * @param {string} summary - Summary text
 * @returns {Promise<Buffer>} - PDF buffer
 */
function generatePDF(reportData, summary) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      // Collect PDF data
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });

      // Header
      doc.fontSize(24)
         .fillColor('#2c3e50')
         .text('Sales Report Summary', { align: 'center' })
         .moveDown(0.5);

      // Date
      doc.fontSize(10)
         .fillColor('#7f8c8d')
         .text(`Generated on: ${new Date().toLocaleDateString('en-US', { 
           year: 'numeric', 
           month: 'long', 
           day: 'numeric' 
         })}`, { align: 'center' })
         .moveDown(2);

      // Summary Section
      doc.fontSize(16)
         .fillColor('#2980b9')
         .text('Executive Summary', { underline: true })
         .moveDown(0.5);

      doc.fontSize(12)
         .fillColor('#34495e')
         .text(summary, { align: 'justify' })
         .moveDown(2);

      // Detailed Report Section
      if (reportData && reportData.report) {
        const report = reportData.report;

        doc.fontSize(16)
           .fillColor('#2980b9')
           .text('Detailed Report', { underline: true })
           .moveDown(0.5);

        // Month and Total
        doc.fontSize(14)
           .fillColor('#2c3e50')
           .text(`Month: ${report.month}`)
           .moveDown(0.3);

        doc.fontSize(14)
           .fillColor('#27ae60')
           .text(`Total Revenue: $${report.total.toLocaleString()}`)
           .moveDown(1);

        // Weekly Breakdown
        doc.fontSize(14)
           .fillColor('#2c3e50')
           .text('Weekly Breakdown:', { underline: true })
           .moveDown(0.5);

        report.weeklyData.forEach((week) => {
          doc.fontSize(12)
             .fillColor('#34495e')
             .text(`  Week ${week.week}: $${week.revenue.toLocaleString()}`, { indent: 20 });
        });
        doc.moveDown(1);

        // Analytics
        if (report.analytics) {
          doc.fontSize(14)
             .fillColor('#2c3e50')
             .text('Analytics:', { underline: true })
             .moveDown(0.5);

          doc.fontSize(12)
             .fillColor('#34495e')
             .text(`  Average Weekly Revenue: $${report.analytics.averageWeekly.toLocaleString()}`, { indent: 20 })
             .moveDown(0.3);

          if (report.analytics.previousMonth) {
            const growthColor = report.analytics.growth >= 0 ? '#27ae60' : '#e74c3c';
            doc.fillColor(growthColor)
               .text(`  Growth vs. ${report.analytics.previousMonth}: ${report.analytics.growthPercentage}%`, { indent: 20 })
               .moveDown(0.3);
          }

          if (report.analytics.highestWeek) {
            doc.fillColor('#34495e')
               .text(`  Highest Week: Week ${report.analytics.highestWeek.week} ($${report.analytics.highestWeek.revenue.toLocaleString()})`, { indent: 20 })
               .moveDown(0.3);
          }

          if (report.analytics.lowestWeek) {
            doc.text(`  Lowest Week: Week ${report.analytics.lowestWeek.week} ($${report.analytics.lowestWeek.revenue.toLocaleString()})`, { indent: 20 });
          }
        }
      }

      // Footer
      doc.moveDown(3);
      doc.fontSize(8)
         .fillColor('#95a5a6')
         .text('Generated by Multi-AI Agent Chatbot System', { align: 'center' })
         .text('Sales Agent • Report Agent • Summary Agent', { align: 'center' });

      // Finalize PDF
      doc.end();

    } catch (error) {
      reject(error);
    }
  });
}

module.exports = { generatePDF };
